version: '3.8'

services:
  db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - .data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    #   - REDIS_HOST=db
    #   - REDIS_PORT=6379
    #   - DB_ADDR = "db:6379"
    #   - DB_PASS = ""
    #   - APP_PORT = "8000"
    #   - DOMAIN = "localhost:8000"
    #   - API_QUOTA = 10
